# Copyright 2026 Rinkia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Turning generated points into files: Markdown documents and the manifest.

Rendering is deliberately separate from generation so the document structure can
change (or grow templates) without touching the pipeline that produces content.
"""

from __future__ import annotations

import os

from modscan.docgen.types import GeneratedPoint
from modscan.fsutil import slugify
from modscan.manifest import build_manifest, write_manifest
from modscan.models import ExampleStatus

# Example file extension and Markdown fence per language.
_LANGUAGE_EXT = {"python": ".py", "javascript": ".js", "typescript": ".ts"}
_EXT_FENCE = {".py": "python", ".js": "javascript", ".ts": "typescript"}
_DEFAULT_EXT = ".ts"
_DEFAULT_FENCE = "typescript"


def example_ext(language: str) -> str:
    return _LANGUAGE_EXT.get(language, _DEFAULT_EXT)


def example_path(point_id: str, ext: str) -> str:
    """Path of an example file, relative to the output directory."""
    return f"examples/{slugify(point_id)}{ext}"


def _fence(path: str) -> str:
    return _EXT_FENCE.get(os.path.splitext(path)[1], _DEFAULT_FENCE)


def _write(path: str, content: str) -> None:
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)


def render_index(overview: str, generated: list[GeneratedPoint]) -> str:
    lines = [
        "# Modding Guide",
        "",
        "> Generated by MODScan. Facts from static analysis; prose from an LLM; "
        "examples validated by loading them.",
        "",
        "## Architecture Overview",
        "",
        overview.strip(),
        "",
        "## Extension Points",
        "",
        "| Point | Category | Location | Example |",
        "| --- | --- | --- | --- |",
    ]
    for gp in generated:
        badge = (
            "UNVERIFIED"
            if gp.example_status == ExampleStatus.UNVERIFIED
            else gp.example_status
        )
        lines.append(
            f"| `{gp.fact.point_id}` | {gp.fact.category} | "
            f"{gp.fact.module}:{gp.fact.lineno} | {badge} |"
        )
    lines += ["", "See [plugin-guide.md](plugin-guide.md) for how to build each one."]
    return "\n".join(lines) + "\n"


def render_guide(generated: list[GeneratedPoint]) -> str:
    lines = ["# Plugin Guide", ""]
    for gp in generated:
        lines += [
            f"## `{gp.fact.point_id}`",
            "",
            f"- **Category:** {gp.fact.category}",
            f"- **Location:** {gp.fact.module}:{gp.fact.lineno}",
            f"- **Example status:** {gp.example_status}",
            "",
            gp.guide.strip(),
            "",
            "### Example",
            "",
        ]
        if gp.example_status == ExampleStatus.UNVERIFIED:
            lines.append("> WARNING: this example could not be validated automatically.")
            lines.append("")
        lines += [
            "```" + _fence(gp.example_path),
            gp.example_code.strip(),
            "```",
            "",
        ]
    return "\n".join(lines) + "\n"


def write_outputs(
    out_dir: str, root: str, overview: str, generated: list[GeneratedPoint]
) -> str:
    """Write every artifact; returns the manifest path."""
    os.makedirs(os.path.join(out_dir, "examples"), exist_ok=True)

    _write(os.path.join(out_dir, "index.md"), render_index(overview, generated))
    _write(os.path.join(out_dir, "plugin-guide.md"), render_guide(generated))
    for gp in generated:
        _write(os.path.join(out_dir, gp.example_path), gp.example_code + "\n")

    manifest_path = os.path.join(out_dir, "extension-points.json")
    write_manifest(manifest_path, build_manifest(root, generated))
    return manifest_path
